Machine Learnig Bootcamp
HomeWork 1

Q1. Pandas version.
What's the version of Pandas that you installed?

In [1]:
import pandas as pd

In [2]:
print((f"Answer of Question 1 is: {pd.__version__}"))

Answer of Question 1 is: 1.5.2


Getting the data,
For this Homework,

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

Cheching the data

In [4]:
data.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

Q2. Records count
How many records are in the dataset?

1 : 4704 <br>
2 : 8704 <br>
3 : 9704 <br>
4 : 17704 <br>

In [5]:
print(f"Answer of Question 2 is: {data.shape[0]}")
#another way to do it is len(data)
print(f"Answer of Question 2 is: {len(data)}")

Answer of Question 2 is: 9704
Answer of Question 2 is: 9704


Q3. Fuel types
How many fuel types are presented in the dataset?

1:  1 <br>
2 : 2 <br>
3 : 3 <br>
4 : 4 <br>

In [6]:
print(f"Answer of Question 3 is: {data['fuel_type'].nunique()}")

Answer of Question 3 is: 2


Q4. Missing values
How many columns in the dataset have missing values? <br>
1 : 0 <br>
2 : 1 <br>
3 : 2 <br>
4 : 3 <br>
5 : 4 <br>

In [7]:
print(f"Answer of Question 4 is: { data.isnull().sum().loc[lambda x : x>0].shape[0] }")

Answer of Question 4 is: 4


Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?<br>

1 : 13.75 <br>
2 : 23.75 <br>
3 : 33.75 <br>
4 : 43.75 <br>

In [8]:
print(f"Answer of Question 5 is: { data[data['origin'] == 'Asia']['fuel_efficiency_mpg'].max()}") 

Answer of Question 5 is: 23.759122836520497


Q6. Median value of horsepower<br>
Find the median value of horsepower column in the dataset.<br>
Next, calculate the most frequent value of the same horsepower column.<br>
Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.<br>
Now, calculate the median value of horsepower once again.<br>
Has it changed?<br>

1 : Yes, it increased <br>
2 : Yes, it decreased <br>
3 : No <br>

In [25]:
median = data["horsepower"].median()
print(f"Median value of horsepower is: {median}")
print(f"Most frequent value of horsepower is: {data['horsepower'].mode()[0]}")
data["horsepower"] = data["horsepower"].fillna(data["horsepower"].mode()[0])
print(f"Median value of horsepower after filling missing values is: {data_filling.median()}")
print(f"missing value : {data['horsepower'].isnull().sum()} ")
print("Answer of question 6 is : Yes, it increased ")

Median value of horsepower is: 152.0
Most frequent value of horsepower is: 152.0
Median value of horsepower after filling missing values is: 152.0
missing value : 0 
Answer of question 6 is : Yes, it increased 


Q7. Sum of weights<br>
Select all the cars from Asia <br>
Select only columns vehicle_weight and model_year<br>
Select the first 7 values<br>
Get the underlying NumPy array. Let's call it X.<br>
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.<br>
Invert XTX.<br>
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].<br>
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.<br>
What's the sum of all the elements of the result?<br>
Note: You just implemented linear regression. We'll talk about it in the next lesson.<br>

1 : 0.051<br>
2 : .51<br>
3 : 5.1<br>
4 : 51<br>

In [26]:
data.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0       152.0     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [35]:
import numpy as np

In [38]:
Asia_cars = data[data["origin"] == "Asia"]
Column_vehicle_model = data[data["origin"] == "Asia"][['vehicle_weight', 'model_year']]
first_7 = Column_vehicle_model.head(7)
X = first_7.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [39]:
Tra = X.T

Transpose

In [41]:
XTX = Tra @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

Invert

In [44]:
INVERT = np.linalg.inv(XTX)
INVERT

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

Creating Array

In [46]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

Findind W

In [47]:
W = INVERT @ Tra @ y
W

array([0.01386421, 0.5049067 ])

Sum of the result of all the elements

In [49]:
W_SUM = W.sum()
print(f"Answer of Question 7 is: {W_SUM}")

Answer of Question 7 is: 0.5187709081074016


Applying linear regression

In [63]:
from sklearn.linear_model import LinearRegression

model = LinearRegression(fit_intercept=False)
len(X), len(y)
model.fit(X, y)

LinearRegression(fit_intercept=False)

In [ ]:
W_Linear = model.coef_
print(W_Linear)
total = np.sum(W_Linear)
print(total)

[0.01386421 0.5049067 ]
0.518770908107402


HomeWork 1 is complete!!